name: CI Tests

on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Pester tests
        shell: pwsh
        run: |
          Install-Module Configuration -AllowClobber -Force
          Invoke-Pester -Passthru